INSERT INTO CITY_BASE_FEE (ID, CITY, BIKE_FEE, SCOOTER_FEE, CAR_FEE)
SELECT 1, 'TARTU', 2.5, 3.0, 3.5
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CITY_BASE_FEE WHERE CITY = 'TARTU');

INSERT INTO CITY_BASE_FEE (ID, CITY, BIKE_FEE, SCOOTER_FEE, CAR_FEE)
SELECT 2, 'TALLINN', 3.0, 3.5, 4.00
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CITY_BASE_FEE WHERE CITY = 'TALLINN');

INSERT INTO CITY_BASE_FEE (ID, CITY, BIKE_FEE, SCOOTER_FEE, CAR_FEE)
SELECT 3, 'PÄRNU', 2.0, 2.5, 3.0
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CITY_BASE_FEE WHERE CITY = 'PÄRNU');

INSERT INTO EXTRA_FEES (ID, VEHICLE, AIR_TEMPERATURE_FEE_UNDER_MINUS10, AIR_TEMPERATURE_FEE_BETWEEN_MINUS10AND0,
                        WIND_SPEED_FEE_BETWEEN10AND20,
                        WIND_SPEED_FEE_OVER20,
                        WEATHER_PHENOMENON_FEE_SNOWY,
                        WEATHER_PHENOMENON_FEE_RAINY,
                        WEATHER_PHENOMENON_FEE_GLAZE
)

SELECT 1, 'CAR', 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM EXTRA_FEES WHERE VEHICLE = 'CAR');

INSERT INTO EXTRA_FEES (ID, VEHICLE, AIR_TEMPERATURE_FEE_UNDER_MINUS10, AIR_TEMPERATURE_FEE_BETWEEN_MINUS10AND0,
                        WIND_SPEED_FEE_BETWEEN10AND20,
                        WIND_SPEED_FEE_OVER20,
                        WEATHER_PHENOMENON_FEE_SNOWY,
                        WEATHER_PHENOMENON_FEE_RAINY,
                        WEATHER_PHENOMENON_FEE_GLAZE
)
SELECT 2, 'BIKE', 1.0, 0.5, 0.5, -1, 1.0, 0.5, -1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM EXTRA_FEES WHERE VEHICLE = 'BIKE');

INSERT INTO EXTRA_FEES (ID, VEHICLE, AIR_TEMPERATURE_FEE_UNDER_MINUS10, AIR_TEMPERATURE_FEE_BETWEEN_MINUS10AND0,
                        WIND_SPEED_FEE_BETWEEN10AND20,
                        WIND_SPEED_FEE_OVER20,
                        WEATHER_PHENOMENON_FEE_SNOWY,
                        WEATHER_PHENOMENON_FEE_RAINY,
                        WEATHER_PHENOMENON_FEE_GLAZE
)
SELECT 3, 'SCOOTER', 1.0, 0.5, 0.0, 0.0, 1.0, 0.5, -1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM EXTRA_FEES WHERE VEHICLE = 'SCOOTER');